apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecommerce-order-service
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: ecommerce-order-service
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: jwt-secret
    - secretKey: password # Has to be this key for mongodb to read it
      remoteRef:
        key: ecommerce-order-service-mongodb-password
