apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-order-service-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: order.jameslucas.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-order-service-service
                port:
                  number: 80
