apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-order-service
spec:
  template:
    spec:
      containers:
        - name: ecommerce-order-service
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-order-service
                  key: jwt_secret
            - name: DB_HOST
              value: "ecommerce-order-service-mongodb-svc"
            - name: DB_PORT
              value: "27017"
            - name: DB_USERNAME
              value: mongodb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-order-service
                  key: password
            - name: RABBITMQ_HOST
              value: "rabbit-mq.default.svc"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq-default-user
                  key: password
            - name: CATALOG_SERVICE_BASE_URL
              value: "http://ecommerce-catalog-service.default.svc:80"
            - name: USER_SERVICE_BASE_URL
              value: "http://ecommerce-user-service.default.svc:80"
            - name: EMAIL_SERVICE_BASE_URL
              value: "http://ecommerce-email-service.default.svc:80"
